# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chat_pb2 as chat__pb2


class ChatServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ChatStream = channel.unary_stream(
        '/chat.ChatServer/ChatStream',
        request_serializer=chat__pb2.Vacio.SerializeToString,
        response_deserializer=chat__pb2.Nota.FromString,
        )
    self.EnviarNota = channel.unary_unary(
        '/chat.ChatServer/EnviarNota',
        request_serializer=chat__pb2.Nota.SerializeToString,
        response_deserializer=chat__pb2.Vacio.FromString,
        )
    self.EnviarNotaInicial = channel.unary_unary(
        '/chat.ChatServer/EnviarNotaInicial',
        request_serializer=chat__pb2.NotaInicial.SerializeToString,
        response_deserializer=chat__pb2.Nota.FromString,
        )
    self.EnviarListaMensajes = channel.unary_unary(
        '/chat.ChatServer/EnviarListaMensajes',
        request_serializer=chat__pb2.Nota.SerializeToString,
        response_deserializer=chat__pb2.ListaNota.FromString,
        )


class ChatServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ChatStream(self, request, context):
    """servicio que permite mantener el streaming del chat asincrono activo entre 2 personas
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnviarNota(self, request, context):
    """servicio que permite enviar mensajes al servidor que procesara luego
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnviarNotaInicial(self, request, context):
    """servicio que permite enviar el primer mensaje, para registrar al cliente nuevo en el servidor
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def EnviarListaMensajes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChatServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ChatStream': grpc.unary_stream_rpc_method_handler(
          servicer.ChatStream,
          request_deserializer=chat__pb2.Vacio.FromString,
          response_serializer=chat__pb2.Nota.SerializeToString,
      ),
      'EnviarNota': grpc.unary_unary_rpc_method_handler(
          servicer.EnviarNota,
          request_deserializer=chat__pb2.Nota.FromString,
          response_serializer=chat__pb2.Vacio.SerializeToString,
      ),
      'EnviarNotaInicial': grpc.unary_unary_rpc_method_handler(
          servicer.EnviarNotaInicial,
          request_deserializer=chat__pb2.NotaInicial.FromString,
          response_serializer=chat__pb2.Nota.SerializeToString,
      ),
      'EnviarListaMensajes': grpc.unary_unary_rpc_method_handler(
          servicer.EnviarListaMensajes,
          request_deserializer=chat__pb2.Nota.FromString,
          response_serializer=chat__pb2.ListaNota.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chat.ChatServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
