version: "3"

services:
  server:

    stdin_open: true
    tty: true

    build: server

    ports:
      - "11912:11912"



  client1:
    depends_on:
      - "server"

    stdin_open: true
    tty: true

    build: client1
    ports:
      - "5001:5001"


  client2:
    depends_on:
      - "server"
      - "client1"

    stdin_open: true
    tty: true
    
    build: client2
    ports:
      - "5002:5002"
